import uuid
from datetime import datetime, timezone

from flask import Blueprint, jsonify, request

from database import get_db

profile_bp = Blueprint('profile', __name__)


def _validate_profile(data):
    """Validate user profile fields. Returns list of error strings."""
    errors = []

    VALID_TECH_LITERACY = {'beginner', 'intermediate', 'advanced'}
    VALID_DIGEST_FREQUENCY = {'daily', 'weekly', 'never'}
    VALID_DIGEST_INTERESTS = {'digital', 'physical', 'both'}

    if 'name' in data:
        name = data.get('name', '')
        if not isinstance(name, str) or not name.strip():
            errors.append('name must be a non-empty string')
        elif len(name.strip()) > 100:
            errors.append('name must be 100 characters or fewer')

    if 'location' in data:
        loc = data.get('location', '')
        if not isinstance(loc, str) or not loc.strip():
            errors.append('location must be a non-empty string')
        elif len(loc.strip()) > 150:
            errors.append('location must be 150 characters or fewer')

    if 'tech_literacy' in data:
        tl = data.get('tech_literacy', '')
        if tl not in VALID_TECH_LITERACY:
            errors.append(f'tech_literacy must be one of: {", ".join(sorted(VALID_TECH_LITERACY))}')

    if 'services' in data:
        svcs = data.get('services')
        if not isinstance(svcs, list):
            errors.append('services must be an array')
        elif not all(isinstance(s, str) for s in svcs):
            errors.append('services must be an array of strings')
        elif len(svcs) > 20:
            errors.append('services must have 20 or fewer items')

    if 'digest_frequency' in data:
        df = data.get('digest_frequency', '')
        if df not in VALID_DIGEST_FREQUENCY:
            errors.append(f'digest_frequency must be one of: {", ".join(sorted(VALID_DIGEST_FREQUENCY))}')

    if 'digest_interests' in data:
        di = data.get('digest_interests', '')
        if di not in VALID_DIGEST_INTERESTS:
            errors.append(f'digest_interests must be one of: {", ".join(sorted(VALID_DIGEST_INTERESTS))}')

    return errors


@profile_bp.route('/profile', methods=['POST'])
def upsert_profile():
    """
    Create or update a user profile.
    Requires client_id in the request body (UUID generated by frontend).
    All other fields are optional — missing fields keep existing values on update.
    """
    data = request.get_json(silent=True)
    if data is None:
        return jsonify({'error': 'Request body must be valid JSON'}), 400

    client_id = (data.get('client_id') or '').strip()
    if not client_id:
        return jsonify({'error': 'client_id is required'}), 400

    errors = _validate_profile(data)
    if errors:
        return jsonify({'error': 'Validation failed', 'details': errors}), 400

    import json as _json
    now = datetime.now(timezone.utc).isoformat()
    services = data.get('services')
    services_json = _json.dumps(services) if services is not None else None

    conn = get_db()
    try:
        cursor = conn.cursor()
        cursor.execute('SELECT client_id FROM user_profiles WHERE client_id = ?', (client_id,))
        existing = cursor.fetchone()

        if existing:
            # Update only provided fields
            updatable = {
                'name':             data.get('name'),
                'location':         data.get('location'),
                'tech_literacy':    data.get('tech_literacy'),
                'services':         services_json,
                'digest_frequency': data.get('digest_frequency'),
                'digest_interests': data.get('digest_interests'),
            }
            updates = {k: v for k, v in updatable.items() if v is not None}
            updates['updated_at'] = now
            updates['client_id'] = client_id

            set_clause = ', '.join(f'{k} = :{k}' for k in updates if k != 'client_id')
            cursor.execute(f'UPDATE user_profiles SET {set_clause} WHERE client_id = :client_id', updates)
        else:
            # Insert new profile
            cursor.execute(
                '''INSERT INTO user_profiles
                   (client_id, name, location, tech_literacy, services, digest_frequency, digest_interests, created_at, updated_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)''',
                (
                    client_id,
                    (data.get('name') or '').strip() or None,
                    (data.get('location') or '').strip() or None,
                    data.get('tech_literacy', 'intermediate'),
                    services_json if services_json is not None else '[]',
                    data.get('digest_frequency', 'weekly'),
                    data.get('digest_interests', 'both'),
                    now,
                    now,
                )
            )

        conn.commit()

        cursor.execute('SELECT * FROM user_profiles WHERE client_id = ?', (client_id,))
        row = dict(cursor.fetchone())
        # Parse services back to list for response
        try:
            row['services'] = _json.loads(row.get('services') or '[]')
        except Exception:
            row['services'] = []

        return jsonify(row), 200 if existing else 201

    finally:
        conn.close()


@profile_bp.route('/profile/<client_id>', methods=['GET'])
def get_profile(client_id):
    """Retrieve a user profile by client_id."""
    import json as _json

    conn = get_db()
    try:
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM user_profiles WHERE client_id = ?', (client_id,))
        row = cursor.fetchone()
        if not row:
            return jsonify({'error': 'Profile not found'}), 404

        profile = dict(row)
        try:
            profile['services'] = _json.loads(profile.get('services') or '[]')
        except Exception:
            profile['services'] = []

        return jsonify(profile), 200
    finally:
        conn.close()
